package com.anton.uzhva.megamazz_bot.model;

public enum ConversationState {
    USER_REGISTRATION,
    WAITING_FOR_REQUEST,
    CHOOSING_EXERCISE,
    INPUTTING_WEIGHT,
    INPUTTING_BODY_WEIGHT,
    WAITING_REPEATING_COUNT,
    CHOOSING_TRAINING_WEEK,
    CREATING_NEW_EXERCISE,
    DELETING_EXERCISE,
    DELETING_ALL_RESULTS,
    BODY_WEIGHT_OPTION,
    СHANGING_USER_NAME,
}
