package com.anton.uzhva.megamazz_bot.model;

public enum ConversationState {//// todo find out states
    USER_REGISTRATION,
    WAITING_FOR_REQUEST, CHOOSING_EXERCISE, INPUTING_RESULT_WEIGHT, WAITING_REPEATING_COUNT, CHOOSING_TRAINING_WEEK, CREATING_NEW_EXERCISE, DELETING_EXERCISE,
}
